[0m[[0m[31merror[0m] [0m[0m/home/michael/Documents/efsm-inference/inference-tool/src/main/scala/inference/Dirties.scala:58:43: not found: type SatisfiabilityUnknownException[0m
[0m[[0m[31merror[0m] [0m[0m      case z3.Status.UNKNOWN => throw new SatisfiabilityUnknownException(g.toString())[0m
[0m[[0m[31merror[0m] [0m[0m                                          ^[0m
[0m[[0m[31merror[0m] [0m[0mone error found[0m
